### PR TITLE
Read comics online

### PR DESCRIPTION
**Pull request by ConradWeiser**
Tested on Beta branch and ready for deployment

### CODE REVIEW

**Comment by ConradWeiser** [comment]
In reality the only changes this branch did is add the Source. Currently it's showing that many more files were added, because it's including #96 as the changes (which was squashed post-pull request)

**Comment by FaizanDurrani** [comment]
I don't exactly know right now if I want to keep the tests in the same repo. So apart from that, it looks good at first glance, I haven't dug deep into it yet tho.

**Comment by ConradWeiser** [comment]
I insist that tests on the same repo are a godsend. Testing sources if they ever have an issue is as simple as running the test, and setting breakpoints in the Mangasee.ts for example. 

Having tests on another repo sounds like jumping through quite a bit of hoops to accomplish the same thing. Why make things harder than it needs to be?
Your call I suppose. It seems like a pain to have tests anywhere else, though.

**Comment by FaizanDurrani** [comment]
My main concern is the build time basically, I don't exactly know if they get built every time with the sources.

**Comment by ConradWeiser** [comment]
Okay, that's a valid concern. I went in and ran tests on bundle times with and without tests.

With tests: 
image
It comes out to be 12 seconds.

Without tests: 
image
It comes out to be 11 seconds.

What do you think?

**Comment by FaizanDurrani** [comment]
1s doesn't really mean much so I am fine with it for now, but if it starts to scale up with sources then it might be better to abstract them out.

**Comment by ConradWeiser** [comment]
I’ll keep an eye on bundle times as sources are added and ensure that it doesn’t grow too much. If so, it should be addressed I agree.

I’m preparing to run a final quality control pass on this source today, and then merge it through.

**Comment by ConradWeiser** [comment]
Search could use some slight refinements to let users make more errors and still have proper results show up, but I'll handle that in a patch. 
Merging

**Pull request merged**
